### ISSUE TITLE
Authentication with more than one group

### ISSUE THREAD

**Issue by kribblo** [mattfysh/sinopia-github#5]
We tried giving access to more than one Organization group, then only the last group (I think) in the list got access. Had to change config to only list one group and make sure all was in that one.

    # only allowed Team Five
    allow_publish: Team One, Team Five

**Comment by mattfysh** [comment]
Hey @kribblo! We use multiple groups too :) try this:

```yaml
allow_publish: [ Team One, Team Five ]
```

If that doesn't work, enclose the group names in double quotes. Let me know!

**Comment by kribblo** [comment]
Ah thanks, that makes sense. Just copied the example from the README :)
